<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admins
 * Date: Fri, 29 Apr 2016 06:23:02 -0400
 */

$conf['title'] = 'WSCC-house';
$conf['lang'] = 'zh';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'gnufdl';
$conf['recent'] = 200;
$conf['showuseras'] = 'username';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['passcrypt'] = 'sha512';
$conf['superuser'] = '@admin';
$conf['manager'] = 'admins';
$conf['disableactions'] = 'register';
$conf['cachetime'] = 0;
$conf['updatecheck'] = 0;

// end auto-generated content
